UPDATE  [dbo].[TABELA PRODUTOS] SET
[EMBALAGEM] = 'Lata',
[PRECO LISTA] = 2.46
WHERE [COD PRODUTO] ='544931'

UPDATE  [dbo].[TABELA PRODUTOS] SET
[EMBALAGEM] = 'Garrafa'
WHERE [COD PRODUTO] ='1078680'


UPDATE [dbo].[TAB VENDEDORES] SET
[PERCENTUAL COMISSAO] = 0.11
WHERE [MATRICULA] = '00238'

UPDATE [dbo].[TAB VENDEDORES] SET
[NOME] = 'José Geraldo da Fonseca Junior'
WHERE [MATRICULA] = '00233'