

ALTER TABLE  [dbo].[TABELA PRODUTOS]
ALTER COLUMN [COD PRODUTO] /* ALTERA A PROPRIEDADE DE UMA COLUNA JÁ EXISTENTE*/
VARCHAR(10) NOT NULL  


ALTER TABLE  [dbo].[TABELA PRODUTOS] /*COMANDO PARA ALTERAR A TABELA JÁ CRIADA*/
ADD CONSTRAINT PK_PRODUTOS 
PRIMARY KEY CLUSTERED ([COD PRODUTO]) /*COMANDO PARA CRIAR A CHAVE PRIMÁRIA OBS: A CHAVE PRIMARIA NAO PODE CONTER VALORES NULL*/



alter table [dbo].[TAB VENDEDORES]
alter column [MATRICULA]
varchar (5) not null

alter table [dbo].[TAB VENDEDORES]
add constraint PK_VENDEDORES
primary key clustered ([MATRICULA])