SELECT * FROM [dbo].[TABELA DE CLIENTES]

SELECT  [CPF]
      ,[NOME]    
  FROM [TABELA DE CLIENTES]

  /* AS é o comando que dá um nome fantasia para o nome da coluna*/
  SELECT  [CPF] AS Identificador
      ,[NOME]   AS Cliente 
  FROM [TABELA DE CLIENTES]

  /*mudado a orde das colunas*/
   SELECT  
      [NOME]   AS Cliente ,
	  [CPF] AS Identificador
  FROM [TABELA DE CLIENTES]

  SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [SABOR] = 'Limão'

  SELECT * FROM [dbo].[TABELA DE VENDEDORES] WHERE [NOME] = 'Cláudia Morais'

 SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] = 4.555

 SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] > 10

 SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] < 10
 SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] <= 4.555
 SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [PREÇO DE LISTA] >= 4.555

 SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [EMBALAGEM] <> 'PET'
 SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [EMBALAGEM] < 'Lata'
 SELECT * FROM [dbo].[TABELA DE PRODUTOS] WHERE [EMBALAGEM] > 'Lata'
 
 SELECT * FROM [dbo].[TABELA DE VENDEDORES] WHERE [PERCENTUAL COMISSAO]>0.1
 SELECT * FROM [dbo].[TABELA DE VENDEDORES] WHERE YEAR ([[DATA ADMISSÃO]) >=2016


  SELECT * FROM [dbo].[TABELA DE CLIENTES] WHERE  YEAR([DATA DE NASCIMENTO]) = 1995
  SELECT * FROM [dbo].[TABELA DE CLIENTES] WHERE  YEAR([DATA DE NASCIMENTO]) < 1995
  SELECT * FROM [dbo].[TABELA DE CLIENTES] WHERE  YEAR([DATA DE NASCIMENTO]) >= 1995

  SELECT * FROM [dbo].[TABELA DE CLIENTES] WHERE  MONTH([DATA DE NASCIMENTO]) = 8
  SELECT * FROM [dbo].[TABELA DE CLIENTES] WHERE  DAY([DATA DE NASCIMENTO]) = 7