INSERT INTO [dbo].[TABELA PRODUTOS]
([COD PRODUTO], [NOME PRODUTO],[EMBALAGEM],[TAMANHO],[SABOR],[PRECO LISTA])
VALUES
('1040107','Light - 350 ml - Melância','Lata','350 ml','Melância',4.56)

INSERT INTO [dbo].[TABELA PRODUTOS]
([COD PRODUTO], [NOME PRODUTO],[EMBALAGEM],[TAMANHO],[SABOR],[PRECO LISTA])
VALUES
('1037797','Clean - 2 Litros - Laranja','PET','2 Litros','Laranja',16.01)

INSERT INTO [dbo].[TABELA PRODUTOS]
([COD PRODUTO], [NOME PRODUTO],[EMBALAGEM],[TAMANHO],[SABOR],[PRECO LISTA])
VALUES
('1000889','Sabor da Montanha - 700 ml - Uva','Garrafa','700 ml','Uva',6.31)




INSERT INTO [dbo].[TAB VENDEDORES]
([MATRICULA],[NOME],[PERCENTUAL COMISSAO])
VALUES
('00233','José Geraldo da Fonseca',0.10)


INSERT INTO [dbo].[TAB VENDEDORES]
([MATRICULA],[NOME],[PERCENTUAL COMISSAO])
VALUES
('00235','José Geraldo da Fonseca',0.08)


INSERT INTO [dbo].[TAB VENDEDORES]
([MATRICULA],[NOME],[PERCENTUAL COMISSAO])
VALUES
('00236','Cláudia Morais',0.08)
